product:
    resource: "@ProductBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

_liip_imagine:
    resource: '@LiipImagineBundle/Resources/config/routing.xml'
